# Generated by Django 5.1.6 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
