# Generated by Django 5.1.6 on 2025-02-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_note_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
